### ISSUE TITLE
Memory Limit Configuration

### ISSUE THREAD

**Issue by fe-lix-** [adobe/aio-lib-runtime#105]
### Expected Behaviour

When configurating an action memory limit in `app.config.yaml` as such : 

```
application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      mypackage:
        actions:
          myactions:
            function: actions/myaction.js
            runtime: 'nodejs:14'
            limits:
              memory: 512
```

The memory limit is not taken into account and the default of 256 is being used.

### Actual Behaviour

The memory limit from `app.config.yaml` should be used.

#### Platform and Version

All platform, `aio-cli:8.3.0`, `@adobe/aio-cli-plugin-runtime:5.4.0` and `@adobe/aio-lib-runtime:4.0.0`

#### Sample Code that illustrates the problem

The problem seems to be here https://github.com/adobe/aio-lib-runtime/blob/b39247d21ccc2b0fbad5359e51c96f5f24933651/src/utils.js#L1014

The documentation [one](https://developer.adobe.com/app-builder/docs/guides/appbuilder-configuration/#runtime-manifest) [two](https://developer.adobe.com/runtime/docs/guides/using/system_settings/) states everywhere we should be using `memory` when the code uses `memorySize`.
