### ISSUE TITLE
Changes to output config.json have broken projects

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-lib-runtime#15]
We used to export the actions to config.json as 
```
{
    "file-list": "https://[NAMESPACE].adobeioruntime.net/api/v1/web/aioappstash-0.0.1/file-list",
    "file-get": " ....
   ...
}
```

Now we are prefixing with the package name:
```
{
    "aioappstash-0.0.1/file-list": "https://[NAMESPACE].adobeioruntime.net/api/v1/web/aioappstash-0.0.1/file-list",
    "aioappstash-0.0.1/file-get": " ....
   ...
}
```

```
import actions from '../config.json'
...
actionWebInvoke(actions['file-list'], headers, params)
// this will now fail with undefined
```

This is the same issue reported by @surajpindoria in slack ...

**Comment by shazron** [comment]
After discussion with the team I believe the way forward is:
1.  Branch off 1.1.0 tag, then publish 1.2.1, essentially reverting https://github.com/adobe/aio-lib-runtime/commit/bc9a3d05b3068457e6b0a2e1a33fe2e84779e95b - this protects existing users that didn't expect the change(s)
2. On the master/main branch, publish 2.0.0 right away. This is so devs that are already relying on 1.2.0 functionality can upgrade to 2.x if they want to keep that functionality (however small the possibility) since 1.2.1 will break them again.

**Comment by shazron** [comment]
## Two issues (breakage):
1. `web-src/src/config.json` now includes the `{package_name-package_version}/` prefixed to the action name as a key. It used to just have the action name.
2. The built `.zip` files (in `dist/actions`) for the actions now include `{package_name-package_version}-` prefixed to the action name as the `.zip` filename.

Note that there is an inconsistency here, the `web-src/src/config.json` file has `{package_name-package_version}/` (trailing slash) as a prefix, while for the `.zip` it has `{package_name-package_version}-` (trailing hyphen) as a prefix (note that this is the name of the folder it zips, so the original issue is the naming of the folder). This should be consistent with a `-`, I don't see a reason why they should be different.

## 1. Proposed fixes for the 1st issue:

All proposed fixes are for backwards compatibility. Assume the package version is `0.0.1` in the examples below.

1. Ensure **action names are unique** for the whole project. Users will not be able to use the same action name for a different package. Keys in `web-src/src/config.json` will not have the `{package_name-package_version}/` prefix.

```yml
packages:
  package_1:
    actions:
      action_1:
      action_2:
  package_2:
    action_3:
    action_4:
```
converts to:
```json
{
    "action_1": "some url",
    "action_2": "some url",
    "action_3": "some url",
    "action_4": "some url"
}
```

2. All keys will have the `{package_name-package_version}/` prefix **EXCEPT** actions from the first package in `manifest.yml`

```yml
packages:
  package_1:
    actions:
      action_1:
      action_2:
  package_2:
    action_1:
    action_2:
```
converts to:
```json
{
    "action_1": "some url",
    "action_2": "some url",
    "package_2-0.0.1/action_1": "some url",
    "package_2-0.0.1/action_2": "some url"
}
```

3. All keys will have the `{package_name-package_version}/` prefix, **no exceptions**. In **addition**, for the first package in `manifest.yml`, we export keys with **only** the action names (no prefix).

```yml
packages:
  package_1:
    actions:
      action_1:
      action_2:
  package_2:
    action_1:
    action_2:
```
converts to:
```json
{
    "package_1-0.0.1/action_1": "some url",
    "package_1-0.0.1/action_2": "some url"
    "package_2-0.0.1/action_1": "some url",
    "package_2-0.0.1/action_2": "some url",
    "action_1": "some url",
    "action_2": "some url"
}
```

## 2. Proposed fix for the 2nd issue:

Right now we have a `builtList` (see [code](https://github.com/adobe/aio-lib-runtime/blob/bfa1a963b0e38224b8af8772acd99a91a06600cc/src/build-actions.js#L149)) that is a result of building the actions and compressing it into a .zip. It is a JavaScript array of absolute file paths to the `.zip` files.

For example, if your app folder is `/my-app`:

```yml
packages:
  package_1:
    actions:
      action_1:
      action_2:
  package_2:
    action_1:
    action_2:
```
the zip list is:
```zip-list.json
[
    "/my-app/dist/actions/package_1-0.0.1-action_1.zip",
    "/my-app/dist/actions/package_1-0.0.1-action_2.zip",
    "/my-app/dist/actions/package_2-0.0.1-action_1.zip",
    "/my-app/dist/actions/package_2-0.0.1-action_2.zip"
]
```

The **proposed fix** is to output this list as a `.json` file in `dist/actions`for other tools to parse. cc @alexkli
