### ISSUE TITLE
utils.getActionUrls returns different action name format if action is in the first package

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-lib-runtime#64]
```
packages:
  pkg1:
     actions:
       my-action:
         web: true
  pkg2:
     actions:
       my-action2:
         web: true
```

would return url object like:
```
{
  'myaction': <url>,
  'pkg2/my-action2': <url>
}
```
the expected should be like:
```
{
  'pkg1/myaction': <url>,
  'pkg2/my-action2': <url>
}
```

Why does this matter ?
Commands calling this method shouldn't need to treat action names differently depending on the package position in the manifest
